### ISSUE TITLE
Вопрос по передаче данных

### ISSUE THREAD

**Issue by MkFair** [shipaz2s/AsioMessengerServer#1]
Здравствуйте, заметил что при получении данных вы выбираете сокет назначения данных и отправляете на него данные, разве данный механизм безопасен? сокеты же могут обрабатываться в разных потоках, при доступе из иного потока операция не является безопастной, или я что-то упустил?

**Comment by shipaz2s** [comment]
Откровенно говоря, я не смогу Вам достоверно ответить на этот вопрос в ближайшее время. Слишком давно не работал с asio и не возвращался к этому коду. При отладке и тестировании этого кода у меня не возникало проблем с совместным использованием данных в потоке.

**Comment by MkFair** [comment]
Спасибо за ответ
